### ISSUE TITLE
[FEAT] is it possible to change the favicon ？

### ISSUE THREAD

**Issue by luyufan498** [linuxserver/docker-chromium#10]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I do want to change the favicon  to be original chrome/chromium Icon.

### Reason for change

The current grey favicon looks like a 404 or unopened page. It is ‘unobtrusive’. 

If I have multiple oponed pages. It is difficult to find it quickly.  

![image](https://github.com/linuxserver/docker-chromium/assets/6166841/ff08fd18-7ad3-4a7a-b403-9ebc94d6eca7)

**Comment by luyufan498** [comment]
Using a light color icon may also be a solution

**Comment by thelamer** [comment]
When it comes to automating this no, that is not something we have considered as it is not text and would require a public URL for a file to ingest or mounting it in. 

But the file is located at `/kclient/public/favicon.ico` in the container if you wanted to mount in a new one you can with `-v /my/favicon/file.ico:/kclient/public/favicon.ico`. I also noticed the simplified Chinese just a note we do support many languages in this container with this mod: 

https://github.com/linuxserver/docker-mods/tree/universal-internationalization

Specifically: 
```
-e DOCKER_MODS=linuxserver/mods:universal-internationalization
-e LC_ALL=zh_CN.UTF-8
```
If you were not aware. 

You can modify the title of the tab as well with the env var `-e TITLE=mytitle` if you want to change that.
