### ISSUE TITLE
[FEAT] GPU support for better performance

### ISSUE THREAD

**Issue by phere-x** [linuxserver/docker-chromium#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have a GPU attached to my machine & is accurately detected (also can be used by other dockerised apps such as Neko's Ungoogled-Chromium).

I wanted to use something like this to have something more bare boned so I can add it as a browser source to OBS

### Reason for change

Better performance

**Comment by thelamer** [comment]
there is gpu support via DRI3, no Nvidia though: 

https://github.com/linuxserver/docker-baseimage-kasmvnc#dri3-gpu-acceleration

You just pass `--device /dev/dri:/dev/dri` and we do the rest.
