### ISSUE TITLE
[FEAT] Would it be possible to add wsEndpoint for use with Puppeteer

### ISSUE THREAD

**Issue by jtapeg** [linuxserver/docker-chromium#16]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would it be possible to add wsEndpoint for use with Puppeteer

### Reason for change

Use with Puppeteer

**Comment by drizuid** [comment]
seems it would be more appropriate for you to use https://www.linuxserver.io/custom

**Comment by thelamer** [comment]
No there are no plans to add this to the default image. I use this base for selenium testing on other projects though and it is relatively easy to achieve. I would recommend working from the base though this is optimized to be used as a web app.
