### ISSUE TITLE
Run chrome in full screen upon launching, also kiosk mode

### ISSUE THREAD

**Issue by huntson** [linuxserver/docker-chromium#18]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'm sure there' some way to do this however I'd like to run the browser in kiosk mode and full screen when the docker launches.  Can this be added if it's not available.

### Reason for change

Cleaner look for stand-alone applications.

**Comment by huntson** [comment]
Is this possible with a command to be able to pass to Chrome within in the container or no way?

**Comment by huntson** [comment]
How am I supposed to keep the from being stale?

**Comment by j0nnymoe** [comment]
Are you not able to pass the flag/settings you want to enable this via the CHROME_CLI env?

**Comment by LudovicTonneaux** [comment]
What I did was modify /usr/bin/wrapped-chromium:
#!/bin/bash

BIN=/usr/bin/chromium

# Cleanup
if ! pgrep chromium > /dev/null;then
  rm -f $HOME/.config/chromium/Singleton*
fi

# Run normally on privved containers or modified un non priv
if grep -q 'Seccomp:\t0' /proc/1/status; then
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --user-data-dir \
  **--kiosk \**
   "$@" > /dev/null 2>&1
else
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --no-sandbox \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --test-type \
  --user-data-dir \
  **--kiosk \**
   "$@" > /dev/null 2>&1
fi

**Comment by LudovicTonneaux** [comment]
adding --kiosk to /usr/bin/wrapped-chromium works
![image](https://github.com/linuxserver/docker-chromium/assets/17905868/636a9cd9-0888-438d-bdfc-f65f4c16e84a)
