### ISSUE TITLE
[BUG] Just blank screen with 8687ac3a-ls43

### ISSUE THREAD

**Issue by ishtangli** [linuxserver/docker-chromium#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Black screen

### Steps To Reproduce

Just run the webui

### Environment

```markdown
- OS: Unraid
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Via unraid app store
```

### Container logs

```bash
No logs created
```

**Comment by j0nnymoe** [comment]
I don't believe there are no logs created. There will be -something- there.

**Comment by danielb7390** [comment]
Same problem, logs look the same as the user above.
tried to right click and open chromium there, nothing.
Tried opening xterm and running `chromium`, no errors, just goes back to the shell.

**Comment by ishtangli** [comment]
Forced a downgrade to previous version for now.

**Comment by derp90** [comment]
Same issue
Here is my log


`2023-12-05 11:06:58.652100+00:00[migrations] started
2023-12-05 11:06:58.652151+00:00[migrations] no migrations found
2023-12-05 11:06:58.819176+00:00usermod: no changes
2023-12-05 11:06:58.819872+00:00───────────────────────────────────────
2023-12-05 11:06:58.819900+00:002023-12-05T11:06:58.819900004Z
2023-12-05 11:06:58.819923+00:00██╗     ███████╗██╗ ██████╗ 
2023-12-05 11:06:58.819936+00:00██║     ██╔════╝██║██╔═══██╗
2023-12-05 11:06:58.819948+00:00██║     ███████╗██║██║   ██║
2023-12-05 11:06:58.819960+00:00██║     ╚════██║██║██║   ██║
2023-12-05 11:06:58.819978+00:00███████╗███████║██║╚██████╔╝
2023-12-05 11:06:58.819991+00:00╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-12-05 11:06:58.820004+00:002023-12-05T11:06:58.820004204Z
2023-12-05 11:06:58.820015+00:00Brought to you by linuxserver.io
2023-12-05 11:06:58.820038+00:00───────────────────────────────────────
2023-12-05 11:06:58.820053+00:002023-12-05T11:06:58.820053779Z
2023-12-05 11:06:58.820065+00:00To support LSIO projects visit:
2023-12-05 11:06:58.820077+00:00https://www.linuxserver.io/donate/
2023-12-05 11:06:58.820095+00:002023-12-05T11:06:58.820095004Z
2023-12-05 11:06:58.820107+00:00───────────────────────────────────────
2023-12-05 11:06:58.820118+00:00GID/UID
2023-12-05 11:06:58.820130+00:00───────────────────────────────────────
2023-12-05 11:06:58.821718+00:002023-12-05T11:06:58.821718418Z
2023-12-05 11:06:58.821737+00:00User UID:    911
2023-12-05 11:06:58.821745+00:00User GID:    911
2023-12-05 11:06:58.821752+00:00───────────────────────────────────────
2023-12-05 11:06:58.821759+00:002023-12-05T11:06:58.821759586Z
2023-12-05 11:06:59.158984+00:00[custom-init] No custom files found, skipping...
2023-12-05 11:06:59.174867+00:00_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2023-12-05 11:06:59.175248+00:002023-12-05T11:06:59.175248180Z
2023-12-05 11:06:59.175274+00:00Xvnc KasmVNC 1.2.0 - built Nov 25 2023 18:39:17
2023-12-05 11:06:59.175288+00:00Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
2023-12-05 11:06:59.175315+00:00See http://kasmweb.com for information on KasmVNC.
2023-12-05 11:06:59.175329+00:00Underlying X server release 12014000, The X.Org Foundation
2023-12-05 11:06:59.175342+00:002023-12-05T11:06:59.175342050Z
2023-12-05 11:06:59.177779+00:00[ls.io-init] done.
2023-12-05 11:06:59.234336+00:00Obt-Message: Xinerama extension is not present on the server
2023-12-05 11:07:46.443040+00:002023-12-05 11:07:46,442 [INFO] websocket 0: got client connection from 127.0.0.1
2023-12-05 11:07:46.461081+00:002023-12-05 11:07:46,460 [PRIO] Connections: accepted: @50.220.114.186_1701774466.443289::websocket`

**Comment by ishtangli** [comment]
Latest release still shows just black.

**Comment by Kamusksn** [comment]
I have the same issue, just black screen after restart the image!

**Comment by dowonim323** [comment]
Same problem, I got log like this

[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-internationalization to container
[mod-init] Downloading linuxserver/mods:universal-internationalization from lscr.io
[mod-init] Installing linuxserver/mods:universal-internationalization
[mod-init] linuxserver/mods:universal-internationalization applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** creating video group video24ic with id 109 ****
**** adding /dev/dri/renderD129 to video group video24ic with id 109 ****
**** permissions for /dev/dri/renderD128 are good ****
**** creating video group videobd0d with id 44 ****
**** adding /dev/dri/card1 to video group videobd0d with id 44 ****
**** permissions for /dev/dri/card0 are good ****
**** International Fonts/Locales installed skipping ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Oct 21 2023 22:22:14
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Error: Access denied
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
xvnc_get_formats
time="2023-12-12T18:46:55.184756605+09:00" level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
 2023-12-12 18:47:02,427 [INFO] websocket 0: got client connection from 127.0.0.1
 2023-12-12 18:47:02,434 [PRIO] Connections: accepted: @***.***.***.***_1702374422.427596::websocket
xvnc_get_formats

**Comment by fate8383** [comment]
I have exact the ama issue last two maybe more versions. Also right click xterm opens but right click chromium selection does nothing...tested on amd and arm instances the same result.

**Comment by drizuid** [comment]
can someone provide a docker run or compose? we can't reproduce this because

![Image](https://github.com/linuxserver/docker-chromium/assets/40674481/5d6fccd7-f696-4105-acac-09ace5c08b3c)

is completely useless

**Comment by danielb7390** [comment]
The docker run command that unraid creates from the template is:

```bash
docker run
  -d
  --name='chromium'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="vault"
  -e HOST_CONTAINERNAME="chromium"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/chromium-logo.png'
  -p '3100:3000/tcp'
  -v '/mnt/user/appdata/chromium/local.conf':'/etc/fonts/local.conf ':'rw'
  -v '/mnt/user/appdata/chromium':'/config':'rw'
  --device='/dev/dri'
  --shm-size=1gb 'lscr.io/linuxserver/chromium' 
```

Already tried to remove the lines:
`  -v '/mnt/user/appdata/chromium/local.conf':'/etc/fonts/local.conf ':'rw'`
`  --device='/dev/dri'` 
to no avail.

**Comment by drizuid** [comment]
> The `docker run` command that unraid creates from the template is:
> 
> ```shell
> docker run
>   -d
>   --name='chromium'
>   --net='bridge'
>   -e TZ="Europe/London"
>   -e HOST_OS="Unraid"
>   -e HOST_HOSTNAME="vault"
>   -e HOST_CONTAINERNAME="chromium"
>   -e 'PUID'='99'
>   -e 'PGID'='100'
>   -e 'UMASK'='022'
>   -l net.unraid.docker.managed=dockerman
>   -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
>   -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/chromium-logo.png'
>   -p '3100:3000/tcp'
>   -v '/mnt/user/appdata/chromium':'/config':'rw'
>   --device='/dev/dri'
>   --shm-size=1gb 'lscr.io/linuxserver/chromium' 
> ```
> 
> EDIT: I got it to work.. just created a new empty `config` directory and it starts, so the problem seems to happen only when there's existing settings?

as you guys are the only ones reporting this, i can't definitively say. i know the --device line is wrong as it should be `--device='/dev/dri:/dev/dri` (as shown in the readme) but i dont think this would cause any problem. I suspect you had something configured that caused a problem and using a clean /config path took that out of play, but again, im guessing due to lack of info

**Comment by danielb7390** [comment]
With `--device` if it's only specified one, it's the host/container path will be the same, afaik
Either way, i tried without `/dev/dri`, the problem remained.

There's no way to debug the chromium process? Like a verbose mode or something?

**Comment by drizuid** [comment]
> There's no way to debug the chromium process? Like a verbose mode or something?

I'm sure chromium has debugging options, but as always, we support the container, not the application within. It is clear that some config in your prior /config path was the issue, assuming you still have that, you could swap it back and check chromium's documentation for debugging to see what caused it

**Comment by danielb7390** [comment]
I understand that this is not the container fault, so any help given is an extra 😅 
I will probably choose the easy way out and just reset the entire chromium...

Meanwhile i saw your edit to open chromium in the terminal, already tried that, it gave no output, it just returns back to the shell

**Comment by drizuid** [comment]
> I understand that this is not the container fault, so any help given is an extra 😅 I will probably choose the easy way out and just reset the entire chromium...
> 
> Meanwhile i saw your edit to open chromium in the terminal, already tried that, it gave no output, it just returns back to the shell

can you try the seccomp unconfined option?

**Comment by danielb7390** [comment]
> > I understand that this is not the container fault, so any help given is an extra 😅 I will probably choose the easy way out and just reset the entire chromium...
> > Meanwhile i saw your edit to open chromium in the terminal, already tried that, it gave no output, it just returns back to the shell
> 
> can you try the seccomp unconfined option?

Tried with ` --security-opt seccomp=unconfined`, same result.
Also tried to remove the ` --shm-size=1gb`, same result.

Quick google search, told me that if i call chromium with `--enable-logging=stderr --v=1 # Output will be printed to standard error (eg. printed in the console) and to the debugger`, yet i get nothing still, process just ends and returns to the shell.

**Comment by drizuid** [comment]
are you using unraid or using that docker run directly?

**Comment by danielb7390** [comment]
I'm editing the unraid template, then checking the generated docker run command.

For the debug line for chromium i used it inside the container in xterm.

**Comment by drizuid** [comment]
when you added in the --security-opt and confirmed it with the docker run, how does it look? can you share it?

**Comment by thelamer** [comment]
The latest version of chromium on alpine 3.18 and 3.19 segfaults, seems like all the time, but on this one container it launches the first time perfectly fine.

I might need to rebase to Debian as there is not a lot of info to go on but give me some time and sorry for the late response here I have been busy. Need to also open up an issue with Alpine.

**Comment by thelamer** [comment]
I'll keep working in the background, but in the mean time I rebased this image to debian.

**Comment by danielb7390** [comment]
Should that change fix the issue? Just tried with latest and same behavior.

**Comment by jessewritescode** [comment]
I also tried `latest` with the same result. In the meantime I was able to get things working by using [98239515-ls42](https://github.com/linuxserver/docker-chromium/releases/tag/98239515-ls42)--I.e., 
```
  chromium:
    # image: lscr.io/linuxserver/chromium:latest
    image: lscr.io/linuxserver/chromium:98239515-ls42
```
if anyone needs a temporary solution until this is resolved

**Comment by AndreiArdelean1** [comment]
With the latest image, now I get an error (with previous images I didn’t have an error)

> Failed to execute child process "/usr/bin/chromium-browser" (No such file or directory)

I’ve checked and in the container there is `/usr/bin/chromium` but no `/usr/bin/chromium-browser`

And here are the container logs:

> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> User UID:    1000
> User GID:    1001
> ───────────────────────────────────────
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> Xvnc KasmVNC 1.2.0 - built Dec 16 2023 18:48:56
> Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
> See http://kasmweb.com for information on KasmVNC.
> Underlying X server release 12014000, The X.Org Foundation
> Obt-Message: Xinerama extension is not present on the server
> /config/.config/openbox/autostart: 2: chromium-browser: not found

**Comment by thelamer** [comment]
Didn't really think about the upgrade scenario that's my fault. Just run `rm /config/.config/openbox/autostart` in the container and restart it in the mean time, ill put a pointer in shortly.

**Comment by thelamer** [comment]
I added a symlink in the latest version. @AndreiArdelean1

**Comment by AndreiArdelean1** [comment]
With the latest inage the error doesn’t show but the browser still doesn’t open.

> 
> 
> User UID:    1000
> User GID:    1001
> ───────────────────────────────────────
> 
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> Xvnc KasmVNC 1.2.0 - built Dec 16 2023 18:48:56
> Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
> See http://kasmweb.com for information on KasmVNC.
> Underlying X server release 12014000, The X.Org Foundation
> 
> Obt-Message: Xinerama extension is not present on the server
> 
> ERROR: openbox-xdg-autostart requires PyXDG to be installed
>  2024-01-01 10:19:42,036 [INFO] websocket 0: got client connection from 127.0.0.1
>  2024-01-01 10:19:42,077 [PRIO] Connections: accepted: @10.0.0.2_1704097182.42580::websocket

**Comment by fate8383** [comment]
> With the latest inage the error doesn’t show but the browser still doesn’t open.
> 
> 
> 
> > 
> 
> > 
> 
> > User UID:    1000
> 
> > User GID:    1001
> 
> > ───────────────────────────────────────
> 
> > 
> 
> > [custom-init] No custom files found, skipping...
> 
> > [ls.io-init] done.
> 
> > _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> > 
> 
> > Xvnc KasmVNC 1.2.0 - built Dec 16 2023 18:48:56
> 
> > Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
> 
> > See http://kasmweb.com for information on KasmVNC.
> 
> > Underlying X server release 12014000, The X.Org Foundation
> 
> > 
> 
> > Obt-Message: Xinerama extension is not present on the server
> 
> > 
> 
> > ERROR: openbox-xdg-autostart requires PyXDG to be installed
> 
> >  2024-01-01 10:19:42,036 [INFO] websocket 0: got client connection from 127.0.0.1
> 
> >  2024-01-01 10:19:42,077 [PRIO] Connections: accepted: @10.0.0.2_1704097182.42580::websocket

The same here

**Comment by thelamer** [comment]
did you try `rm /config/.config/openbox/autostart` and restart. I cannot reproduce on my end the debian base works.

**Comment by derp90** [comment]
> did you try `rm /config/.config/openbox/autostart` and restart. I cannot reproduce on my end the debian base works.

I tried that and just a blank screen for me as well

**Comment by thelamer** [comment]
What is the output if you right click the desktop and run xterm from there run chromium-brpwser or wrapped-chromium?
Also try seccomp unconfined

**Comment by derp90** [comment]
> seccomp unconfined

![image](https://github.com/linuxserver/docker-chromium/assets/32005229/a8d673f9-d98f-402b-b6bb-adae9ed37724)

**Comment by AndreiArdelean1** [comment]
Removing `/config/.config/openbox/autostart` has no effect
Removing the `/config/.config/chromium` solves the problem but resets the settings
Removing all from `/config/.config/chromium` except the `Default` directory solves the problem and keeps the settings

I already had `seccomp:unconfined` set.

Running:
- `chromium-browser` has no effect
- `wrapped-chromium` has no effect
<img width="928" alt="Screenshot 2024-01-05 at 09 37 46" src="https://github.com/linuxserver/docker-chromium/assets/9552100/7527aa70-eb2d-4139-9994-49a45543b426">

**Comment by drizuid** [comment]
> > seccomp unconfined
> 
> ![image](https://private-user-images.githubusercontent.com/32005229/294421394-a8d673f9-d98f-402b-b6bb-adae9ed37724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc4MzEsIm5iZiI6MTcwNDQ1NzUzMSwicGF0aCI6Ii8zMjAwNTIyOS8yOTQ0MjEzOTQtYThkNjczZjktZDk4Zi00MDJiLWI2YmItYWRhZTllZDM3NzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyMjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjhhZWUyMGRkOWNiYjE5NWM4NTY4ZDExNzM0NTg1MTE4ZGNhMDA3YTA5ZWQ3ZDdkMGQzNzJjYjU5OTMyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjKGK4Arx07xmLxH_CDhFJE4ysDRNeAO1Ks4Okj-EVg)

it's not a command, look at the readme and put the seccomp:unconfined in your docker run/compose.

**Comment by drizuid** [comment]
> Removing `/config/.config/openbox/autostart` has no effect Removing the `/config/.config/chromium` solves the problem but resets the settings Removing all from `/config/.config/chromium` except the `Default` directory solves the problem and keeps the settings
> 
> I already had `seccomp:unconfined` set.
> 
> Running:
> 
> * `chromium-browser` has no effect
> * `wrapped-chromium` has no effect
> 
> <img alt="Screenshot 2024-01-05 at 09 37 46" width="928" src="https://private-user-images.githubusercontent.com/9552100/294424716-7527aa70-eb2d-4139-9994-49a45543b426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc4MzEsIm5iZiI6MTcwNDQ1NzUzMSwicGF0aCI6Ii85NTUyMTAwLzI5NDQyNDcxNi03NTI3YWE3MC1lYjJkLTQxMzktOTk5NC00OWE0NTU0M2I0MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTIyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM5ZjlhY2MxYjdlOTNjY2RlNzM0MzhkMDA0MzU4MjhkNTVmMzA0MGJiODA0YWFlNjJlOGQ5ZTBhNGI3NmRkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ht0RKBgtESxhG4DjRZwyzGAUjf21idH6JdbaqTne-NY">

if tells you in the error that it was left locked to avoid corruption. poss an unclean shutdown/restart. if you google that error, it tells you how to unlock it. that is what is preventing chromium from starting.

**Comment by fate8383** [comment]
rm -rf ~/.config/chromium/Singleton*

Running this command fixed it for me, thanks.

**Comment by derp90** [comment]
Running rm -rf ~/.config/chromium/SingletonLock
Will fix the issue until the container is restarted

**Comment by derp90** [comment]
> > > seccomp unconfined
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/32005229/294421394-a8d673f9-d98f-402b-b6bb-adae9ed37724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc4MzEsIm5iZiI6MTcwNDQ1NzUzMSwicGF0aCI6Ii8zMjAwNTIyOS8yOTQ0MjEzOTQtYThkNjczZjktZDk4Zi00MDJiLWI2YmItYWRhZTllZDM3NzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyMjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjhhZWUyMGRkOWNiYjE5NWM4NTY4ZDExNzM0NTg1MTE4ZGNhMDA3YTA5ZWQ3ZDdkMGQzNzJjYjU5OTMyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjKGK4Arx07xmLxH_CDhFJE4ysDRNeAO1Ks4Okj-EVg)
> 
> it's not a command, look at the readme and put the seccomp:unconfined in your docker run/compose.

Whoops, misunderstood that.

I'm actually running it in kubernetes (truenas Scale) so all the docker options are not fully available to me. 
If you would like I can link you an instance of a chromium for debugging purposes

**Comment by thelamer** [comment]
Inside the web interface you can right click the desktop to open xterm, running the bin manually might show is where it is faulting

**Comment by AndreiArdelean1** [comment]
> > Running:
> > 
> > * `chromium-browser` has no effect
> > * `wrapped-chromium` has no effect
> > 
> > <img alt="Screenshot 2024-01-05 at 09 37 46" width="928" src="https://private-user-images.githubusercontent.com/9552100/294424716-7527aa70-eb2d-4139-9994-49a45543b426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc4MzEsIm5iZiI6MTcwNDQ1NzUzMSwicGF0aCI6Ii85NTUyMTAwLzI5NDQyNDcxNi03NTI3YWE3MC1lYjJkLTQxMzktOTk5NC00OWE0NTU0M2I0MjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTIyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM5ZjlhY2MxYjdlOTNjY2RlNzM0MzhkMDA0MzU4MjhkNTVmMzA0MGJiODA0YWFlNjJlOGQ5ZTBhNGI3NmRkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ht0RKBgtESxhG4DjRZwyzGAUjf21idH6JdbaqTne-NY">
> 
> if tells you in the error that it was left locked to avoid corruption. poss an unclean shutdown/restart. if you google that error, it tells you how to unlock it. that is what is preventing chromium from starting.

When I run the commands, nothing shows up in either the console or the logs

**Comment by AndreiArdelean1** [comment]
Is the `SingletonLock` symlink broken? The file to which it points doesn't exist. The same for `SingletonCookie`

```
root@004f37ee3c32:~/.config/chromium# readlink -f /config/.config/chromium/SingletonLock
/config/.config/chromium/004f37ee3c32-349
root@004f37ee3c32:~/.config/chromium# ls /config/.config/chromium/
 AutofillStates             extensions_crx_cache         'Last Version'                        'Safe Browsing'         'Subresource Filter'
 BrowserMetrics-spare.pma   FileTypePolicies             'Local State'                          SafetyTips              TpcdMetadata
 CertificateRevocation      first_party_sets.db           MEIPreload                            segmentation_platform   TrustTokenKeyCommitments
 component_crx_cache        first_party_sets.db-journal   OnDeviceHeadSuggestModel              ShaderCache             Variations
'Crash Reports'             FirstPartySetsPreloaded       OptimizationHints                     SingletonCookie         ZxcvbnData
'Crowd Deny'                GraphiteDawnCache             OriginTrials                          SingletonLock
 Default                    GrShaderCache                 PKIMetadata                           SingletonSocket
 Dictionaries               hyphen-data                   PrivacySandboxAttestationsPreloaded   SSLErrorAssistant
```


```
lrwxrwxrwx  1 abc abc       18 Jan  8 10:14  SingletonCookie -> 840014527782887287
lrwxrwxrwx  1 abc abc       16 Jan  8 10:14  SingletonLock -> 004f37ee3c32-349
lrwxrwxrwx  1 abc abc       50 Jan  8 10:14  SingletonSocket -> /tmp/.org.chromium.Chromium.Z45301/SingletonSocket
```

**Comment by thelamer** [comment]
This container got rebased you probably need to purge your home directory or at least `/config/.config/chromium`

**Comment by derp90** [comment]
> This container got rebased you probably need to purge your home directory or at least `/config/.config/chromium`

Wiping the config directory works for the first boot, but any reboots and blank screen issue returns.

**Comment by thelamer** [comment]
I added a hook to clear out these singleton files if chromium is not running, please test this tag and let me know: 

lsiodev/chromium:amd64-4fed82c2-pkg-4fed82c2-dev-38e474cb898ef1652d55a867d3c18245f8a12d1b

**Comment by derp90** [comment]
> I added a hook to clear out these singleton files if chromium is not running, please test this tag and let me know:
> 
> lsiodev/chromium:amd64-4fed82c2-pkg-4fed82c2-dev-38e474cb898ef1652d55a867d3c18245f8a12d1b

This seems to be working for me, multiple restarts with no issues

**Comment by danielb7390** [comment]
> I added a hook to clear out these singleton files if chromium is not running, please test this tag and let me know:
> 
> lsiodev/chromium:amd64-4fed82c2-pkg-4fed82c2-dev-38e474cb898ef1652d55a867d3c18245f8a12d1b
Working for me too.

**Comment by Truth1984** [comment]
same issue, i'm running as root, so I have to add `--no-sandbox` to args to launch.

**Comment by justinh998** [comment]
> same issue, i'm running as root, so I have to add `--no-sandbox` to args to launch.
Sorry for what is probably a stupid question, but I have just encountered the same problem and I'm not sure how to include this environment variable in my Docker compose.

**Comment by Truth1984** [comment]
@justinh998 set your $PUID $PGID to 0, replace `$CHROME_CLI` content with --no-sandbox; or checkout my forked project, which covers the majority of the (normal ) cli use case
