### ISSUE TITLE
[FEAT] Add emoji support

### ISSUE THREAD

**Issue by danielb7390** [linuxserver/docker-chromium#22]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add some sort of emoji package to this docker image.

### Reason for change

Just browsing the web you will end up finding some emojis around, and currently they are just not rendered.

![image](https://github.com/linuxserver/docker-chromium/assets/5844389/13557d90-314b-4233-8bb5-c23437b18782)

### Proposed code change

Add `fonts-noto-color-emoji` to the image

**Comment by thelamer** [comment]
This can be achieved with: 

```
-e DOCKER_MODS=linuxserver/mods:universal-package-install
-e INSTALL_PACKAGES=fonts-noto-color-emoji
```

I am still debating adding all the langs and CJK fonts along with emoji in the baseimage.

**Comment by thelamer** [comment]
This is now in by default

**Comment by sunny693** [comment]
> This can be achieved with:
> 
> ```
> -e DOCKER_MODS=linuxserver/mods:universal-package-install
> -e INSTALL_PACKAGES=fonts-noto-color-emoji
> ```
> 
> I am still debating adding all the langs and CJK fonts along with emoji in the baseimage.

That would be great.
