### ISSUE TITLE
Way to pass additional flags when executing xvnc

### ISSUE THREAD

**Issue by kevinmnm** [linuxserver/docker-chromium#23]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

What would be the easiest way to pass additional flags to xvnc such as `-nocursor`? Would be great if there's a straightforward approach or documentation on this.

### Reason for change

I need to hide VNC cursor (e.g. `-nocursor`) from server and I'm having hard time trying to locate where in Dockerfile I should modify exactly.

**Comment by thelamer** [comment]
No as far as  I know KasmVNC and noVNC do not support hiding the cursor. Depending on what you need to achieve though you can make the window view only and disable the control bar on the side. But you are gonna need to hack around with the default settings passed here: 

https://github.com/linuxserver/kclient/blob/master/public/index.html#L17

I don't have any plans to make this a docker env flag, but you are welcome to modify kclient to your desires and fork something that suits your specific development needs.
