### ISSUE TITLE
[FEAT] Auto-restart Chrome if accidentally exited 

### ISSUE THREAD

**Issue by seanmikhaels** [linuxserver/docker-chromium#24]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Implement feature to auto restart chrome processes if exited by accident. 

### Reason for change

Avoid restarting entire container to relaunch chrome

**Comment by aptalca** [comment]
Right click on the background

**Comment by seanmikhaels** [comment]
> Right click on the background

Easy enough, thank you!
