### ISSUE TITLE
[FEAT]  Web VNC + Option for Standard VNC Fat Client via Port 5600

### ISSUE THREAD

**Issue by seanmikhaels** [linuxserver/docker-chromium#25]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Implement option for WEB or Think Client access via Port 5600

### Reason for change

Preference for thick client as well as web

**Comment by j0nnymoe** [comment]
Kasmvnc doesn't have a thick client option. It's designed for web access.

Unless kasm put this into kasmvnc, we won't get it.
