### ISSUE TITLE
[FEAT] Add open a new private window manu

### ISSUE THREAD

**Issue by rui8832** [linuxserver/docker-chromium#26]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add open a new private window manu.

### Reason for change

I need a private window when debugging my web app.

### Proposed code change

Add a menu item to the `root/defaults/menu.xml` file:

```
<item label="Chromium Private" icon="/usr/share/icons/hicolor/48x48/apps/chromium.png"><action name="Execute"><command>/usr/bin/wrapped-chromium --incognito</command></action></item>
```

**Comment by thelamer** [comment]
Can you put this in the format of a PR and add release notes to the readme-vars.yaml ?
