### ISSUE TITLE
[BUG] Multiple dependencies missing (PyXDG, Xinerama etc)

### ISSUE THREAD

**Issue by privacyadmin** [linuxserver/docker-chromium#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fresh install on a newly formatted system with Docker on Fedora 40 Server.
Running the image resulted in on first run resulted in "openbox-xdg-autostart requires PyXDG". Installing python3-xdg resolves this issue but returns this error "Xinerama extension is not present on the server" this time

### Expected Behavior

Chromium browser should be shown

### Steps To Reproduce

1. Run container
2. Install python3-xdg to resolve openbox-xdg-autostart requires PyXDG
3. Restart container
4. New error "Xinerama extension is not present on the server"

### Environment

```markdown
- OS: Fedora 40
- How docker service was installed:
dnf install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - /example/Docker/chromium/config:/config
    ports:
      - 8855:8855
    shm_size: "1gb"
    restart: unless-stopped
```

### Container logs

```bash
───────────────────────────────────────
[custom-init] No custom files found, skipping...
Xvnc KasmVNC 1.2.0 - built Jun 26 2024 18:56:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
19
```

**Comment by thelamer** [comment]
If you want to see something fun go ahead and change this line to not pipe to null: 
https://github.com/linuxserver/docker-chromium/blob/master/root/usr/bin/wrapped-chromium#L30

It is just Openbox warnings and they have no effect on the functionality of the container. We are running Desktop apps and DEs inside a Docker container with the minimal set of software needed to run the underlying application. There will be all kinds of Nag messages depending on the app/DE.

**Comment by privacyadmin** [comment]
![image](https://github.com/linuxserver/docker-chromium/assets/162864564/1593cb9c-0f2a-417e-8a28-72f157082f6b)

I thought those errors might have been causing this blank screen.

Any clue on what might have cause this problem?

**Comment by thelamer** [comment]
right click the desktop, open a terminal and run `chromium` see what it spits out. Use `chromium --no-sandbox` if you are running without seccomp unconfined.

**Comment by privacyadmin** [comment]
Got it and much thanks for the support
