### ISSUE TITLE
[BUG] CPU Usage Spike

### ISSUE THREAD

**Issue by ishtangli** [linuxserver/docker-chromium#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CPU usage spikes when this docker is on even when nobody is connected

### Expected Behavior

Little to no CPU utilization while idle.

### Steps To Reproduce

1. Turn on docker
2. Check unraid dashboard

### Environment

```markdown
- OS: Unraid
- How docker service was installed: Unraid apps tab
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid apps tab
```

### Container logs

```bash
to follow
```

**Comment by ishtangli** [comment]
Logs:

[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Jul  6 2024 18:59:17
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
17
 2024-07-11 13:03:34,584 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-07-11 13:03:34,592 [PRIO] Connections: accepted: @121.58.233.130_1720674214.585084::websocket

**Comment by jlssmt** [comment]
I can confirm this problem.
and that is the main issue that prevents the use of this image.

**Comment by jlssmt** [comment]
Please don't stale

**Comment by j0nnymoe** [comment]
Provide some proof of the processes within the container spiking and we can investigate further.
