### ISSUE TITLE
[FEAT] Ungoogled Chromium support

### ISSUE THREAD

**Issue by extremelyonline** [linuxserver/docker-chromium#4]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello, is there any plan to incorporate Ungoogled Chromium instead of Chromium?

### Reason for change

To improve privacy

### Proposed code change

It may be difficult to build Ungoogled Chromium in the Dockerfile, perhaps the flatpak version can be used?

**Comment by thelamer** [comment]
That would actually be a new image (this one does what it is supposed to), and would likely need to be built from source. 

Given the current state of the ungoogled project probably Arch Linux using AUR would be the best base.

If you want to get the wheels turning take a look at how AUR packages get installed here: 
https://github.com/linuxserver/docker-baseimage-kasmvnc/blob/arch/Dockerfile#L304-L307
Use the arch baseimage and try it out yourself, or from an arch webtop to see how it works: 
https://github.com/linuxserver/docker-webtop#version-tags
