### ISSUE TITLE
[Font] is there any solution to support chinese font?

### ISSUE THREAD

**Issue by luyufan498** [linuxserver/docker-chromium#9]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want to access some page with with chinese font.  But it looks like this 
![image](https://github.com/linuxserver/docker-chromium/assets/6166841/fa1dd9f2-1597-48c4-8f42-c35a7eac71b2)
 Is there any varible like ENABLE_CJK_FONT=1?

### Reason for change

It should benfit users who want to access chinese website.

**Comment by thespad** [comment]
Have a look at https://github.com/linuxserver/docker-mods/tree/universal-internationalization

**Comment by luyufan498** [comment]
> Have a look at https://github.com/linuxserver/docker-mods/tree/universal-internationalization

thanks, it works
